name: Deploy Dental Intel Stack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SERVER_IP: 206.81.11.59
  PRIVATE_IP: 10.116.0.2

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm run install:all
    
    - name: Run tests
      run: |
        npm run test
    
    - name: Build applications
      run: |
        npm run build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Deploy to production
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ env.SERVER_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /opt/dental-intel/current
          git pull origin main
          git submodule update --recursive
          docker-compose -f docker-compose.prod.yml up -d --build
          
          # Health check
          sleep 30
          curl -f http://${{ env.PRIVATE_IP }}:5000/health
          curl -f http://localhost:80
